Change rocketchat::install API to allow setting the bundle URL directly
seekingalpha/puppet-rocket pull request #1
Opened 2020-08-25 14:46 UTC by nmagedman

2020-08-27 15:04 UTC, kapcod requested changes

2020-08-27 15:04 UTC, kapcod commented on manifests/install.pp
> +    undef   => $package_source ? {
Please convert it to if/elsif/else one-level flow.

2020-08-27 15:04 UTC, kapcod commented on manifests/params.pp
> +  $bundle_url         = undef
How is params.pp used?

2020-08-27 18:34 UTC, kapcod commented on manifests/params.pp
> +  $bundle_url         = undef
Ok, I paid attention now to your message where you said "I’m not clear on the difference between params.pp".
@reist Do you know?

2020-08-30 12:32 UTC, nmagedman commented
While I _do_ prefer being able to specify the URL _explicitly_ and _directly_ — rather than separately via a "source", an "ensure" (whatever _that_ is), and a buried, internally defined template — the _existing_ API is nonetheless sufficient for specifying the URL as we currently want it.

So this PR is not necessary, and I'm dropping it.

2020-08-30 12:32 UTC, closed without merging